---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: dummy-app-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dummy-app-1 
  name: dummy-app-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi